//go:build darwin

// Sensor key definitions adapted from https://github.com/dkorunic/iSMC
// (GPLv2+, Copyright 2019 Dinko Korunic). Generated from smc/sensors.go.
package smc

type sensorStat struct {
	key  string
	desc string
}

// appleTemp is the full list of known Apple SMC temperature keys.
// Keys containing "%" are wildcard patterns expanded 0–9 at runtime.
var appleTemp = []sensorStat{
	{"TA%P", "Ambient %"},
	{"Th%H", "Heatpipe %"},
	{"TZ%C", "Thermal Zone %"},
	{"TC%D", "CPU Diode %"},
	{"TC%E", "CPU Diode Virtual %"},
	{"TC%F", "CPU Diode Filtered %"},
	{"TC%H", "CPU Heatsink %"},
	{"TC%P", "CPU Proximity %"},
	{"TCAD", "CPU Package"},
	{"TC%c", "CPU Core %"},
	{"TC%C", "CPU Core %"},
	{"TCGC", "GPU Intel Graphics"},
	{"TG%D", "GPU Diode %"},
	{"TGDD", "GPU AMD Radeon"},
	{"TG%H", "GPU Heatsink %"},
	{"TG%P", "GPU Proximity %"},
	{"Tm%P", "Mainboard %"},
	{"Tp%P", "Powerboard %"},
	{"TB%T", "Battery %"},
	{"TW%P", "Airport %"},
	{"TL%P", "Display %"},
	{"TI%P", "Thunderbolt %"},
	{"TH%A", "Disk % (A)"},
	{"TH%B", "Disk % (B)"},
	{"TH%C", "Disk % (C)"},
	{"TN%D", "Northbridge Diode %"},
	{"TN%H", "Northbridge Heatsink %"},
	{"TN%P", "Northbridge Proximity %"},
	{"Tp09", "CPU Efficiency Core 1"},
	{"Tp0T", "CPU Efficiency Core 2"},
	{"Tp01", "CPU Performance Core 1"},
	{"Tp05", "CPU Performance Core 2"},
	{"Tp0D", "CPU Performance Core 3"},
	{"Tp0H", "CPU Performance Core 4"},
	{"Tp0L", "CPU Performance Core 5"},
	{"Tp0P", "CPU Performance Core 6"},
	{"Tp0X", "CPU Performance Core 7"},
	{"Tp0b", "CPU Performance Core 8"},
	{"Tg05", "GPU 1"},
	{"Tg0D", "GPU 2"},
	{"Tg0L", "GPU 3"},
	{"Tg0T", "GPU 4"},
	{"Tm02", "Memory 1"},
	{"Tm06", "Memory 2"},
	{"Tm08", "Memory 3"},
	{"Tm09", "Memory 4"},
	{"Tp1h", "CPU Efficiency Core 1"},
	{"Tp1t", "CPU Efficiency Core 2"},
	{"Tp1p", "CPU Efficiency Core 3"},
	{"Tp1l", "CPU Efficiency Core 4"},
	{"Tp0f", "CPU Performance Core 7"},
	{"Tp0j", "CPU Performance Core 8"},
	{"Tg0f", "GPU 1"},
	{"Tg0j", "GPU 2"},
	{"Te05", "CPU Efficiency Core 1"},
	{"Te0L", "CPU Efficiency Core 2"},
	{"Te0P", "CPU Efficiency Core 3"},
	{"Te0S", "CPU Efficiency Core 4"},
	{"Tf04", "CPU Performance Core 1"},
	{"Tf09", "CPU Performance Core 2"},
	{"Tf0A", "CPU Performance Core 3"},
	{"Tf0B", "CPU Performance Core 4"},
	{"Tf0D", "CPU Performance Core 5"},
	{"Tf0E", "CPU Performance Core 6"},
	{"Tf44", "CPU Performance Core 7"},
	{"Tf49", "CPU Performance Core 8"},
	{"Tf4A", "CPU Performance Core 9"},
	{"Tf4B", "CPU Performance Core 10"},
	{"Tf4D", "CPU Performance Core 11"},
	{"Tf4E", "CPU Performance Core 12"},
	{"Tf14", "GPU 1"},
	{"Tf18", "GPU 2"},
	{"Tf19", "GPU 3"},
	{"Tf1A", "GPU 4"},
	{"Tf24", "GPU 5"},
	{"Tf28", "GPU 6"},
	{"Tf29", "GPU 7"},
	{"Tf2A", "GPU 8"},
	{"TaLP", "Airflow Left"},
	{"TaRF", "Airflow Right"},
	{"TH0x", "NAND"},
	{"TB1T", "Battery 1"},
	{"TB2T", "Battery 2"},
	{"TW0P", "Airport"},
	{"TCSA", "PECI SA"},
	{"Ts0S", "Memory Proximity"},
	{"TM0P", "Mem Bank A1"},
	{"TM1P", "Mem Bank A2"},
	{"TM8P", "Mem Bank B1"},
	{"TM9P", "Mem Bank B2"},
	{"TM0S", "Mem Module A1"},
	{"TM1S", "Mem Module A2"},
	{"TM8S", "Mem Module B1"},
	{"TM9S", "Mem Module B2"},
	{"TN0C", "MCH Die"},
	{"TP0D", "PCH Die"},
	{"TPCD", "PCH Die"},
	{"TP0P", "PCH Proximity"},
	{"Ts0P", "Palm Rest"},
	{"Tb0P", "BLC Proximity"},
	{"TH0P", "HDD Bay 1"},
	{"TH1P", "HDD Bay 2"},
	{"TH2P", "HDD Bay 3"},
	{"TH3P", "HDD Bay 4"},
	{"TO0P", "Optical Drive"},
	{"TS0C", "Expansion Slots"},
	{"TA0S", "PCI Slot 1 Pos 1"},
	{"TA1S", "PCI Slot 1 Pos 2"},
	{"TA2S", "PCI Slot 2 Pos 1"},
	{"TA3S", "PCI Slot 2 Pos 2"},
	{"ALT0", "Ambient Light Sensor Temperature 1"},
	{"ALT1", "Ambient Light Sensor Temperature 2"},
	{"TA0V", "Ambient Virtual"},
	{"TA0p", "Ambient 1 Raw"},
	{"TA1p", "Ambient 2 Raw"},
	{"TA2p", "Ambient 3 Raw"},
	{"TC0J", "CPU PECI Die Max Error"},
	{"TC0T", "CPU PECI Die Trend"},
	{"TC0d", "CPU Die Raw"},
	{"TC0p", "CPU Proximity Raw"},
	{"TCMX", "Max PECI Reported"},
	{"TCXR", "CPU Max Package Core Relative Cooked"},
	{"TCXr", "CPU Max Package Core Relative Raw"},
	{"TG0E", "GPU 0 Die Filtered For Fan Control"},
	{"TG0F", "GPU 0 Die Filtered And Adjusted For Power Control"},
	{"TG0J", "GPU 0 Die Max Error"},
	{"TG0M", "GFX Memory"},
	{"TG0T", "GPU Die Analog"},
	{"TG0d", "GPU 0 Die Raw"},
	{"TG0p", "GPU 0 Proximity Raw"},
	{"TG1F", "GPU 1 Die Filtered"},
	{"TG1d", "GPU 1 Die Raw"},
	{"TG1p", "GPU 1 Proximity Raw"},
	{"TG2p", "GPU 2 Proximity Raw"},
	{"TG3p", "GPU 3 Proximity Raw"},
	{"TH0F", "Drive OOBv3 Relative Filtered Max"},
	{"TH0O", "Drive 0 OOBv1 Mapped"},
	{"TH0R", "Drive 0 OOBv3 Relative Cooked Max"},
	{"TH0V", "SSD B Foreign Drive Prediction"},
	{"TH0X", "SSD 0 OOBv3 Cooked Max"},
	{"TH0a", "Drive 0 OOBv3 Absolute Raw A"},
	{"TH0b", "Drive 0 OOBv3 Absolute Raw B"},
	{"TH0c", "Drive 0 OOBv3 Absolute Raw C"},
	{"TH0o", "Drive 0 OOBv1 Raw Bit-Mapped"},
	{"TH1F", "SSD 1"},
	{"TH1O", "Drive 1 OOBv1 Mapped"},
	{"TH1R", "SSD 1"},
	{"TH1X", "SSD 1 OOBv3 Cooked Max"},
	{"TH1a", "Drive 1 OOBv3 Absolute Raw A"},
	{"TH1b", "Drive 1 OOBv3 Absolute Raw B"},
	{"TH1c", "Drive 1 OOBv3 Absolute Raw C"},
	{"TH1o", "Drive 1 OOBv1 Raw Bit-Mapped"},
	{"THFH", "Fin Stack"},
	{"THSP", "Thunderbolt Die"},
	{"TI0T", "Thunderbolt Proximity Cooked"},
	{"TI0p", "TBT Proximity Raw"},
	{"TL0V", "LCD Filtered Right Front-Of-Screen Virtual"},
	{"TL0p", "LCD UnFiltered Front-Of-Screen Raw"},
	{"TL1V", "LCD TL1v-Filtered Center Front-Of-Screen"},
	{"TL1p", "LCD TCON Proximity Raw"},
	{"TL2p", "LCD IR Target Hotspot Raw"},
	{"TL3p", "LCD IR Sensor Die Raw"},
	{"TM0D", "DIMM 0 PECI Cooked"},
	{"TM0V", "Drive 0 Sensor Existence"},
	{"TM0p", "DIMM 0 Proximity Raw"},
	{"TM1D", "DIMM 1 PECI Cooked"},
	{"TM1p", "DIMM 1 Proximity Raw"},
	{"TM2D", "DIMM 2 PECI Cooked"},
	{"TM2P", "DIMM 0/1 VR Proximity Cooked"},
	{"TM2p", "DIMM 2 Proximity Raw"},
	{"TM3D", "DIMM 3 PECI Cooked"},
	{"TM3P", "DIMM 2/3 VR Proximity Cooked"},
	{"TM3p", "DIMM 3 Proximity Raw"},
	{"TMBS", "DIMM Bandwidth Estimate"},
	{"TMCD", "Memory Controller/Integrated Graphics PECI"},
	{"TMLB", "Dimm Proximity"},
	{"TMXD", "DIMM Max Cooked"},
	{"TMXP", "DIMM Proximity Max Cooked"},
	{"TPCd", "PCH Digital Die Raw"},
	{"TS0D", "Speaker Remote"},
	{"TS0P", "Speaker Proximity"},
	{"TS0V", "Skin 0 Virtual"},
	{"TS0p", "Skin 0 Raw"},
	{"TS1D", "Speaker Remote 2"},
	{"TS1P", "Speaker Proximity 2"},
	{"TS2P", "S2 Camera Proximity"},
	{"TTF0", "Fan Target"},
	{"TV0P", "Vent Proximity"},
	{"TVFP", "Filtered Vent Proximity"},
	{"TW0p", "Wifi Proximity Raw"},
	{"Ta0P", "DCIn Air Flow"},
	{"TaSP", "DCIn Air Flow Adjusted"},
	{"Tb0p", "Backlight Controller Proximity Raw"},
	{"Te0T", "TBT Thermal Diode"},
	{"Te0t", "TBT Thermal Diode Raw"},
	{"Th0N", "Nand"},
	{"Th0P", "Heat Spreader Proximity"},
	{"Th0R", "RIO"},
	{"Tm0p", "EMC1428 Internal Diode Raw"},
	{"Tm1p", "MLB Proximity 1 Raw"},
	{"Tm2p", "MLB Proximity 2 Raw"},
	{"Tp2F", "Power Supply T2 Secondary Heatsink Filtered"},
	{"Tp2H", "Power Supply T2 Secondary Heatsink Cooked"},
	{"Tp2h", "Power Supply T2 Secondary Heatsink Raw"},
	{"Ts1P", "Actuator"},
	{"Ts1S", "Synthetic Top Skin"},
	{"TTLD", "Thunderbolt Left"},
	{"TTRD", "Thunderbolt Right"},
	{"TaLT", "Thunderbolt Left Proximity"},
	{"TaRT", "Thunderbolt Right Proximity"},
}
